// Generated by LiveScript 1.2.0
var _, request;
_ = require('prelude-ls-extended');
request = require('request');
exports['default'] = function(it){
  switch (it.data.type) {
  case 'mxDone':
    if (_.chance(0.9)) {
      request('http://localhost:5672/job', {
        json: {
          type: 'cf',
          data: {
            domainId: it.data.domainId
          }
        }
      }, function(err, response){
        it.done(err);
      });
    } else {
      request('http://localhost:5672/job', {
        json: {
          data: {
            type: 'done',
            domainId: it.data.domainId
          }
        }
      }, function(err, response){
        it.done(err);
      });
    }
    break;
  case 'done':
    console.log('Your entire campaign has finished for domainId:', it.data.domainId);
  }
};
exports.campaign = function(it){
  var domainId;
  console.log('Inserting stuff into the database and doing things');
  if (_.chance(0.2)) {
    return it.error('Things randomly crashed');
  }
  domainId = it.data.domainId;
  if (!domainId) {
    return it.error('Invalid domainId');
  }
  it.create({
    jobs: [
      {
        type: 'mx1',
        data: {
          domainId: domainId
        }
      }, {
        type: 'mx2',
        data: {
          domainId: domainId
        }
      }
    ],
    onComplete: {
      data: {
        type: 'mxDone',
        domainId: domainId
      }
    }
  });
  it.done(err);
};
exports.mx1 = function(it){
  var metric;
  if (_.chance(0.1)) {
    return it.done('Getting metrics failed');
  }
  metric = _.rand(10);
  if (_.chance(0.1)) {
    return it.done('Saving metrics failed');
  }
  it.done();
};
exports.mx2 = function(it){
  var metric;
  if (_.chance(0.1)) {
    return it.done('Getting metrics failed');
  }
  metric = _.rand(10);
  if (_.chance(0.1)) {
    return it.done('Saving metrics failed');
  }
  it.done();
};
exports.cf = function(it){
  if (_.chance(0.1)) {
    return it.done('Finding contacts failed');
  }
  request('http://localhost:5672/job', {
    json: {
      data: {
        type: 'done',
        domainId: it.data.domainId
      }
    }
  }, function(err, response){
    it.done(err);
  });
};